# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94172e0a43b14e47097a96b6ddb1b92c36c2295776e001b2c9388f0261910514fdcf7f497bac175ba32aef1a78dc1d09f8e1a84eb359a68d1212c79c2438bbec

test:
  secret_key_base: 76dbe833d20b6cc4f4c3ff8e04a3b1fe0250da674ee2a9fa01d358d09ebe70a198f6544ad8b67deafe4dca43074dcb3f56538883894ffc11217610604859a354

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
